# Generated by Django 5.0.3 on 2024-03-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_video_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='img',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
